version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

#  kibana:
#   image: docker.elastic.co/kibana/kibana:7.10.0
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    volumes:
      - .:/usr/src/app

volumes:
  esdata:

